DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export MONOHZZ4L_PATH=$DIR
export PATH=$MONOHZZ4L_PATH/bin:$PATH
export DELPHES=$HOME/external/delphes
export PYTHIA=$HOME/external
export DYLD_LIBRARY_PATH=$PYTHIA/lib:$DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH=$DELPHES:$PYTHIA/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$MONOHZZ4L_PATH/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$MONOHZZ4L_PATH/lib:$DYLD_LIBRARY_PATH
export PYTHONPATH=$MONOHZZ4L_PATH/python:$PYTHONPATH


